### ISSUE TITLE
Error installing vim-heads.v9.0.0846.20230331_072825.zos.pax.Z

### ISSUE THREAD

**Issue by gngrossi** [ZOSOpenTools/vimport#15]
https://github.com/ZOSOpenTools/vimport/releases/download/vimport_840/vim-heads.v9.0.0846.20230331_072825.zos.pax.Z

installing vim
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     25      0 --:--:-- --:--:-- --:--:--    25
1 block
FSUM7131 Out of space or reached the end of the archive file.
 If you want to go on, type device or file name when ready

**Comment by IgorTodorovskiIBM** [comment]
Ah, thank you. This is a result of a recent CI/CD pipeline change, probably affects all new releases. Will take a look

**Comment by IgorTodorovskiIBM** [comment]
Should be better now

**Comment by gngrossi** [comment]
Looks good...thanks
