### ISSUE TITLE
Remove - and validate - that the environment variable does not need to be set in the shell 

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/vimport#30]
In [buildenv](https://github.com/ZOSOpenTools/vimport/blob/6e5e0c282ba3893f70c28e54b9930395022976fd/buildenv#L31) we should only need to set the environment variables on in the binary (e.g. keep zopen_append_to_zoslib_env and remove zopen_append_to_env)

**Comment by IgorTodorovskiIBM** [comment]
This is now complete
