### ISSUE TITLE
arrow keys don't have an effect

### ISSUE THREAD

**Issue by IgorTodorovskiIBM** [ZOSOpenTools/vimport#6]
when editing in vim, the arrow keys do not move the cursor

**Comment by IgorTodorovskiIBM** [comment]
Looks like TERM=dtterm was the culprit. Setting TERM=xterm fixes it

**Comment by MikeFultonDev** [comment]
@IgorTodorovskiIBM closing this since I'm assuming it's fixed. re-open if not (arrow keeys work fine for me!)
