### ISSUE TITLE
turning syntax on does not give colors

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/vimport#9]
:syntax on provides underline / bold but no colors
Is this a bug? Google seems to indicate that's all that is needed... 
@IgorTodorovskiIBM

**Comment by IgorTodorovskiIBM** [comment]
What is your TERM set to? I have it set to TERM=xterm

**Comment by IgorTodorovskiIBM** [comment]
Ok, I think you need this in your .vimrc:
```
syntax on
set t_Co=8
set t_Sf=^[[3%p1%dm
set t_Sb=^[[4%p1%dm
```

**Comment by IgorTodorovskiIBM** [comment]
I think we can change the defaults for these in the code

**Comment by MikeFultonDev** [comment]
@IgorTodorovskiIBM those set commands didn't work for me. Can I cut'n'paste those or are they some sort of escape sequence?

**Comment by IgorTodorovskiIBM** [comment]
I have those in my ~/.vimrc

**Comment by MikeFultonDev** [comment]
now that ncurses is exporting TERMINFO, I am able to get this to work!
